version: '3'

services:
  app:
    image: 'golang:1.9.1'
    volumes:
      - 'data:/go'
      - '.:/go/src/app'
    ports:
      - '1323:1323'
    command: bash -c "cd /go/src/app && go run *.go"

volumes:
  data:
    driver: 'local'