version: '3'

services:
  app:
    image: 'golang:1.9.1'
    volumes:
      - 'data:/go'
      - '.:/go/src/app'
    ports:
      - '8080:8080'
    command: 'go run /go/src/app/main.go'

volumes:
  data:
    driver: 'local'